### ISSUE TITLE
GraphViewer ToDo-List

### ISSUE THREAD

**Issue by Shadow992** [UniFormal/MMT#207]
# Short Description

- [ ] means "not solved yet", 
- [x] means "basic idea solved but subitems may not have been solved yet" 
- [ ] ~~XYZ~~ means "We thought about adding XYZ but could not implement it or did not want to implement it"

(P2-T1) means "the priority to implement this lies at 2 (range 1 to 10; where 10 is highest priority)" and "the time consumed is 1 (range 1 to 10; where 10 is highest time needed to implement)"

So something like this
- [x] Make tea (P10-T5)
  - [ ] Different flavor (P2-T10)
  - [x] Cook water (P10-T3)

can be read as:

"We finished the basic idea of making tea, which had highest priority (P10) and moderate time consumed (T5). However we still need to enable different flavors to finish the whole project."

# Graph-Viewer ToDo List 
- [x] Zoom in/out (P10-T1)
  - [x] Crop (P10-T1)
  - [ ] Cluster (maybe drop this) (P3-T3)
- [x] Cluster graph (P10-T2)
  - [x] using (P10-T1)
    - [x] new nodes (P10-T1)
    - [x] color (P5-T1)
    - [ ] boxes (P5-T3)
    - [ ] regions (P5-T5)
    - [ ] hiding (P5-T7)
    - [ ] Add Legend for Clustering (e.g. Show: "Red - Cluster1") (P3-T7)
  - [x] Select nodes by (P10-T1)
    - [x] path name (P7-T?)
    - [ ] meta theory (P7-T?)
    - [ ] dependency (P7-T?)
    - [ ] free hand drawing (P7-T4)
    - [ ] query (P5-T9)
  - [ ] Save clustered graphs (using backend) (P3-T8)
- [x] Extend context menu (on node right click) (P10-T2)
  - [x] Open in new window (P10-T1)
  - [x] Show URI (P10-T1)
  - [ ] Show declaration (P10-T4)
  - [ ] Infer type (P10-T?)
  - [x] Open cluster (P10-T2)
- [ ] Edit graph (P8-T2)
  - [ ] Save graph in backend? (P2-T8)
  - [ ] Add Theory/MPD Editor (P?-T10)
- [ ] Highlight/Hide paths (P7-T5)
- [x] Beautify UI (P1-T10)
  - [x] Restyling (P8-T2)
  - [ ] Add Navigation (left side) (P9-T5)
  - [ ] Add Theories/Structures/Views in Text-Mode (P3-T10)
- [x] Merge MPD and Basic-Graph-Viewer (P10-T4)
- [ ] Implement own Hierarchical-Layout-Algorithm (P1-T10)

# Links
Live Demo: http://neuralocean.de/graph/theorygraph.php?uri=test/pvs.json

**Comment by kohlhase** [comment]
This looks very good, I am looking forward to more blue check marks appearing. 
Could you put the link to the demo into the description above, then I always know where to look.

**Comment by Shadow992** [comment]
Moved to new repo: https://github.com/UniFormal/TGView/issues/2
